import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'
import type { Itinerary } from './travel-types'

export function generateItineraryPDF(itinerary: Itinerary) {
  const doc = new jsPDF()

  // Colors
  const primaryColor: [number, number, number] = [232, 125, 62] // #e87d3e (brand primary)
  const textColor: [number, number, number] = [60, 60, 60]

  // Header Title
  doc.setFontSize(24)
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2])
  doc.text(`Itinerary: ${itinerary.destination}`, 14, 22)

  // Subheader
  doc.setFontSize(11)
  doc.setTextColor(textColor[0], textColor[1], textColor[2])
  const dateRange = `${format(new Date(itinerary.startDate), 'MMM d, yyyy')} - ${format(
    new Date(itinerary.endDate),
    'MMM d, yyyy'
  )}`
  
  doc.text(`Dates: ${dateRange}`, 14, 32)
  
  // Format duration helper
  const formatDuration = (minutes: number) => {
    if (minutes < 60) return `${minutes} min`
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
  }

  let finalY = 42

  // Loop through days
  itinerary.days.forEach((day, index) => {
    // Add page if needed
    if (finalY > 250) {
      doc.addPage()
      finalY = 20
    }

    // Day Header
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text(`Day ${index + 1} - ${format(new Date(day.date), 'EEEE, MMMM d')}`, 14, finalY)
    
    // Day Stats
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`Distance: ${day.totalDistance} km | Total Time: ${formatDuration(day.totalDuration)}`, 14, finalY + 6)
    
    finalY += 10

    // Prepare table data
    const tableData = day.places.map((place) => [
      `${place.startTime} - ${place.endTime}`,
      place.name,
      place.address || 'N/A',
      formatDuration(place.duration),
      place.price || '-',
    ])

    // Generate Table
    autoTable(doc, {
      startY: finalY,
      head: [['Time', 'Place Name', 'Address', 'Duration', 'Price']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: primaryColor,
        textColor: 255,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 10,
        cellPadding: 4,
      },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 45 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 25 },
        4: { cellWidth: 20 },
      },
    })

    // Update finalY for the next day
    finalY = (doc as any).lastAutoTable.finalY + 15
  })

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.text(
      `Generated by Voyager Travel`,
      14,
      doc.internal.pageSize.height - 10
    )
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 25,
      doc.internal.pageSize.height - 10
    )
  }

  return doc
}

export function exportItineraryToPDF(itinerary: Itinerary) {
  const doc = generateItineraryPDF(itinerary)
  const sanitizedDestination = itinerary.destination.replace(/[^a-z0-9]/gi, '_').toLowerCase()
  doc.save(`${sanitizedDestination}_itinerary.pdf`)
}
